apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonita-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bonita
  template:
    metadata:
      labels:
        app: bonita
    spec:
      containers:
        - name: bonita
          image: bonita:latest
          env:
            - name: TENANT_LOGIN
              valueFrom:
                secretKeyRef:
                  name: bonita-secret
                  key: TenantUser
            - name: TENANT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bonita-secret
                  key: TenantPassword
          ports:
            - containerPort: 8080
