apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bonita-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bonita-postgres
  template:
    metadata:
      labels:
        app: bonita-postgres
    spec:
      containers:
        - name: bonita-postgres
          image: bonitasoft/bonita-postgres
          ports:
            - containerPort: 5432
