apiVersion: v1
kind: Secret
metadata:
  name: bonita-secret
type: Opaque
data:
  TENANT_LOGIN: YWRtaW4=
  TENANT_PASSWORD: cGFzc3dvcmQ=
  DB_USER: Ym9uaXRh
  DB_PASS: YnBt
  BIZ_DB_USER: YnVzaW5lc3NfZGF0YQ==
  BIZ_DB_PASS: YnBt
