apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonita-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bonita
  template:
    metadata:
      labels:
        app: bonita
    spec:
      initContainers:
        - name: copy-ro-scripts
          image: busybox
          command:
            ["sh", "-c", "cp /scripts/script.sh /opt/custom-init.d/script.sh"]
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
            - name: pre-install
              mountPath: /opt/custom-init.d/
      containers:
        - name: bonita
          image: bonita:latest
          env:
            - name: TENANT_LOGIN
              valueFrom:
                secretKeyRef:
                  name: bonita-secret
                  key: TENANT_LOGIN
            - name: TENANT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bonita-secret
                  key: TENANT_PASSWORD

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bonita-config
                  key: DB_HOST

            - name: DB_VENDOR
              valueFrom:
                configMapKeyRef:
                  name: bonita-config
                  key: DB_VENDOR

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: bonita-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: bonita-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: bonita-secret
                  key: DB_PASS
            - name: BIZ_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: bonita-config
                  key: BIZ_DB_NAME
            - name: BIZ_DB_USER
              valueFrom:
                secretKeyRef:
                  name: bonita-secret
                  key: BIZ_DB_USER
            - name: BIZ_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: bonita-secret
                  key: BIZ_DB_PASS
          volumeMounts:
            - name: pre-install
              mountPath: /opt/custom-init.d/
          ports:
            - containerPort: 8080
      volumes:
        - name: pre-install
          emptyDir: {}
        - name: script-volume
          configMap:
            name: bonita-init-script
