apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonita-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bonita
  template:
    metadata:
      labels:
        app: bonita
    spec:
      initContainers:
        - name: copy-ro-scripts
          image: busybox
          command:
            ["sh", "-c", "cp /scripts/script.sh /opt/custom-init.d/script.sh"]
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
            - name: pre-install
              mountPath: /opt/custom-init.d/
      containers:
        - name: bonita
          image: bonita:latest
          env:
            - name: TENANT_LOGIN
              valueFrom:
                secretKeyRef:
                  name: bonita-secret
                  key: TenantUser
            - name: TENANT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bonita-secret
                  key: TenantPassword
            - name: DB_HOST
              value: bonita-postgres-service
            - name: DB_VENDOR
              value: postgres
            - name: DB_NAME
              value: bonita
            - name: DB_USER
              value: bonita
            - name: DB_PASS
              value: bpm
            - name: BIZ_DB_NAME
              value: business_data
            - name: BIZ_DB_USER
              value: business_data
            - name: BIZ_DB_PASS
              value: bpm
          volumeMounts:
            - name: pre-install
              mountPath: /opt/custom-init.d/
          ports:
            - containerPort: 8080
      volumes:
        - name: pre-install
          emptyDir: {}
        - name: script-volume
          configMap:
            name: bonita-init-script
